#!/usr/bin/env bash

HAS_NODE=`which node 2> /dev/null`

#
# There are some issues with Source Tree because paths are not set correctly for
# the given environment. Sourcing the bash_profile seems to resolve this for bash users,
# sourcing the zshrc for zshell users.
#
# https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly
#
function source_home_file {
  file="$HOME/$1"
  [[ -f "${file}" ]] && source "${file}"
}

if [[ -z "$HAS_NODE" ]]; then
  source_home_file ".bash_profile" || source_home_file ".zshrc" || source_home_file ".bashrc" || true
fi

NODE=`which node 2> /dev/null`
LOCAL="/usr/local/bin/node"
BINARY=
GIT_ROOT_DIR=

#
# Figure out which binary we need to use for our script execution.
#
if [[ -n "$NODE" ]]; then
  BINARY="$NODE"
elif [[ -x "$LOCAL" ]]; then
  BINARY="$LOCAL"
fi

#
# Add --dry-run cli flag support so we can execute this hook without side affects
# and see if it works in the current environment
#
if [[ $* == *--dry-run* ]]; then
  if [[ -z "$BINARY" ]]; then
    exit 1
  fi
else
  GIT_ROOT_DIR=$(pwd)
  cd $(dirname $(readlink -f "$0"))
  "$BINARY" "$("$BINARY" -e "console.log(require.resolve('pre-commit-enhanced'))")" "$GIT_ROOT_DIR"
fi
